// <auto-generated />
namespace find_job.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ad5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ad5));
        
        string IMigrationMetadata.Id
        {
            get { return "201712240148427_ad5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
